### ISSUE TITLE
Offset removed twice in Software/EmonCT1

### ISSUE THREAD

**Issue by MohammedBENHADINE** [openenergymonitor/STM32#18]
Greetings,

While migrating from emonTx to STM32 based energy monitoring , i used this repo to make a working solution.
But i noticed that in the main.c of the EmonCT1 example , the offset is removed in two locations : 

1.     The first time is located at the process_frame function , while processing each sample : `          signed_V = sample_V - MID_ADC_READING`

2.    The second time is at the end of processing , by substruction of the RMS of the offset (the mean) : `       sum_I_sq_copy -= (Imean*Imean);
` 
Regards,
Mohammed

**Comment by danbates2** [comment]
Hi Mohammed,
If you could post this question to the forum at https://community.openenergymonitor.org/ that'd be great.

But yes, you're correct and it's an interesting point. Thanks.

**Comment by MohammedBENHADINE** [comment]
Thanks for the rapid reply.
I'll make sure next time to post on the forum.

To continue on the remark , i've used the second method to remove the offset ,bcz it makes more sense in my brain to use a mathematical formula , RMS (U1+U2) = square((RMS(U1)^2 + RMS(U2)^2).

- U1 = the offset

- U2 = the burden voltage without offset

- U1+U2 = the actual signal sampled by the ADC

I thank you guys for the hard work behind the scenes.
Cheers,
